### PR TITLE
Add replaceDeployUrl method

### PR DESCRIPTION
**Pull request by kayvanbree**
Added a slightly different method than I used in my project, because I couldn't use this. This should work, but I don't know how you test and stuff...

### CODE REVIEW

**Comment by kyubisation** [comment]
I'm not convinced that the library needs this specific functionality. I'd rather leave this to the consumer of this library.
For example; Should the vendor chunk be considered? What about common? What about potential additional/custom scripts added manually?
You could also do this replacement in a one-liner:
```
config.regexReplace(/(src=|href=)(")(runtime|scripts|main|polyfills|styles)/g, `$1$2${deployUrl}$3`)
```

**Comment by kayvanbree** [comment]
I'm not sure what you mean by vendor chunk. 

We could just add a chapter to the readme explaining how to work with the deploy url?

**Comment by kyubisation** [comment]
I apologize for the radio silence.
Vendor and common chunks are configurable via the angular cli. If we support this functionality, we should also include these.
This also doesn't address usage of --deploy-url, since the current regex only matches use cases where --deploy-url wasn't used (`<script src="runtime...js"></script>` vs `<script src="https://example.com/runtime...js"></script>`).
By the way, is your project with the base href publicly available?

**Comment by kayvanbree** [comment]
It's not. Old school company, so no open source. I could maybe recreate it and run an example on my own server, but I had trouble with my Jenkins shutting down. I'll try to get something done after work. I do have another project I want to run a demo app for first though.

**Pull request closed without merging**
