### PR TITLE
WIP: Add Native CLI for inserting variables

### PR DESCRIPTION
**Pull request by DanielHabenicht**
Implements #23

### CODE REVIEW

**Comment by DanielHabenicht** [comment]
You are welcome to test the working prototypes (packed in this [go-cli.zip](https://github.com/kyubisation/angular-server-side-configuration/files/2948416/go-cli.zip)). 
File size will be between 1-2MB. 

How do you want to hook up the cli to the other one? 
I think it would be good to wire the native cli (just for the insert command) through your npm cli, when developing. In order to not have two different feature sets. 

For production the user can copy the matching cli for his OS.

**Comment by kyubisation** [comment]
Thank you very much for your contribution! 👍 
I will have a look at it as soon as possible.
I will give it some thought on how to best integrate it with the existing CLI. What I would prefer is to ship the go implementation of the insert command as a WebAssembly module and to link to that. (https://github.com/golang/go/wiki/WebAssembly)
I'm currently working on version 2, which will support an alternative to process.env.* (NG_ENV.*). I would like to integrate this for the final/stable 2.0.0 release.

**Comment by kyubisation** [comment]
This week I have been thinking about the architecture of this library, in light of #22.
So for version 2 I will separate detection and insertion. Detection will only be done at compile time and insertion at runtime (as before). This will also allow me to use TypeScript for detection.

I want to provide two ways to generate the required information. One will create a ngssc.json file in dist and the other will embed the information into the index.html in dist.

ngssc.json Schema:
```
{
  /** Pattern for files that should have variables inserted */
  filePattern: string = 'index.html',
  /** Whether to recursively look for files matching filePattern */
  recursiveMatching: boolean = true,
  /** The variant to insert */
  variant: 'process' | 'NG_ENV' = 'process',
  /** The environment variables to insert */
  environmentVariables: string[],
}
```

index.html Pattern:
Example: `<!--CONFIG {"variant":"NG_ENV","environmentVariables":["BACKEND_URL","PROD_MODE"]]}-->`
```
{
  /** The variant to insert */
  variant: 'process' | 'NG_ENV' = 'process',
  /** The environment variables to insert */
  environmentVariables: string[],
}
```

I would very much appreciate it, if you would help me with the Go implementation. If you lack the time, I will try to adapt the code you have written so far.
Either way, thank you very much for the work you have provided.

**Comment by DanielHabenicht** [comment]
I think it is a good idea to separate both tasks. 
Next week I can go ahead and implement the new logic in go.

Just some Questions: 
Is there a particluar reason to write the config into the `index.html` instead of just copying the `ngssc.json` to the `dist` folder and than apply it in producation? I think it`s confusing to have the configuration in multiple files and this approach is more consistent. 

The WebAssembly approach is to early on I think. There is no documentation whatsoever on how to link a command-line-tool or even a node-js application with WebAssembly. It might be easier to just pass the arguments to the executable (or make two command line tools...)

**Comment by kyubisation** [comment]
Sorry; It seems I forgot to actually save/post my comment.
What I wanted to reply:
The acceptance of additional files in the output is relatively low in my experience (and looking at the success/euphoria of zero configuration tools and embedding configuration in package.json).
I'm close to finishing my announced work. Afterwards I will try to adapt your implementation, assuming you did not yet have time to work on it.

As for WebAssembly; From what I understand WASM has been possible since Node 8, but yeah, the official documentation has been lacking.
I am in no hurry to merge the go cli into the existing cli and would prefer to provide it separately in an initial release.

**Comment by kyubisation** [comment]
I have reduced the ngssc insert command to two use cases. I will try today to adapt your implementation.

Usage: ngssc insert [options] [directory]

Insert environment variables. Looks for an ngssc.json file inside the current or given directory.
Alternatively use the --config-in-html flag. (Directory defaults to current working directory)

| Options | Description |
| --- | --- |
| `-i, --config-in-html`      | Recursively searches for html files and applies the configuration found inside |
| `--dry`                     | Perform the insert without actually inserting the variables |

**Comment by DanielHabenicht** [comment]
Cool, is there anything I can do or do you already implemented the missing flags? 
I'm participating in a hackathon this Friday maybe I can get some stuff done. 

Something else I wanted to ask was: 
Do you think it should be possible to set some variables in other files (e.g. `opensearch.xml` or `index.html`) with this tool? 

My future use case of this cli asks for it. Because I want to deploy my angular application on different base-urls or even domains and still want to be able to correctly set up the `opensearch.xml` file without rebuilding. 
I am doing it with sed logic over here: 
Openseach.xml: https://github.com/T-Systems-MMS/phonebook/blob/master/Phonebook.Frontend/src/assets/opensearch.xml
and https://github.com/T-Systems-MMS/phonebook/blob/master/Phonebook.Frontend/substitute_variables.sh

**Comment by kyubisation** [comment]
I have already implemented most of it, but testing still needs to be done. I will try to push my implementation this evening. If possible I would like you to have a look at it, since I most certainly broke quite a few Golang Best Practices.

As for the replacement use case; I have been thinking about this, since I have a similar use case.
I'd like to provide an additional (optional) field in ngssc.json:
```json
...
  "replacements": [
    {
      "filePattern": "index.html",
      "replace": "<!--TOKEN-->",
      "with": "some example value"
    }
  ]
...
```

Would this be enough for your use case?

**Comment by DanielHabenicht** [comment]
Ok, I am looking forward to testing what you've implemented. I am also new to GoLang but I can have a look. 

I think the config should not be static, as I want to be able to dynamically change it via ENV variables. 
My idea would be: 
```jsonc
...
    /* I think it is a better name in order to make clear that these are not the normal replacements done by this cli */
    "additonalReplacements": [
        {
            /* glob Pattern to search the files */
            "filePattern": "*.xml",
            /* the environment variable that should be used to replace the token ${BASE_URL} <- The token is named like the environment variable in order to follow standards from sed or setenv commands */
            "environmentVariable": "BASE_URL"
        }
    ]
...
```
this would replace something like this with the url from the environment variable:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/" 
  xmlns:moz="http://www.mozilla.org/2006/browser/search/">
  <Image width="16" height="16" type="image/x-icon">${BASE_URL}/favicon.ico</Image>
  <Url type="text/html" template="${BASE_URL}/search/{searchTerms}"/>
</OpenSearchDescription>
```

**Comment by kyubisation** [comment]
I have pushed my changes to develop. The code is working. but I will have to optimize the build chain.

In regards to the additional replacements use case; Sounds reasonable. However I would like to focus on releasing the current state and would implement this in version 2.1.0.

**Pull request merged**
